### ISSUE TITLE
Can we see the code for the demo?

### ISSUE THREAD

**Issue by hrigoberto** [jpb12/react-tree-graph#5]
I would like to see just exactly how the demo is being implemented. Could the code for it be added to the repo?

**Comment by jpb12** [comment]
Do you mean [this](https://github.com/jpb12/tree-viewer)?

**Comment by jpb12** [comment]
As well as the linked repository, you can also see the code on the actual demo site.  It's always deployed as a development build with source maps included so that the code is viewable, though it's not in the most intuitive place if you're not familiar with webpack bundles.

![source](https://user-images.githubusercontent.com/2174430/31378516-7c7ab12c-ada3-11e7-90ff-f7d0d85cfe13.png)

**Comment by hrigoberto** [comment]
That's perfect thanks!

I tried finding it in the source maps but I guess I wasn't looking hard enough.
