### ISSUE TITLE
Warning: flattenChildren(...): Encountered two children with the same key

### ISSUE THREAD

**Issue by CharlesCarnell** [jpb12/react-tree-graph#6]
```
Warning: flattenChildren(...): Encountered two children with the same key, `0:$Level 4: B`. Child keys must be unique; when two children share a key, only the first child will be used.
```

Getting this whilst loosely replicating your demo, is this a React warning that should be ignored whilst using this library?

![image](https://user-images.githubusercontent.com/10024311/31673673-c108281a-b357-11e7-97ea-50f8033cb461.png)

Kind regards.

``` javascript
   const data = {
      name: 'Top Level',
      attributes: {
        keyA: 'val A',
        keyB: 'val B',
        keyC: 'val C',
      },
      children: [
        {
          name: 'Level 2: A',
          attributes: {
            keyA: 'val A',
            keyB: 'val B',
            keyC: 'val C',
          },
          children: [
            {
              name: 'Level 3: A',
              children: [
                {
                  name: 'Level 4: A'
                },
                {
                  name: 'Level 4: B',
                  children: [
                    {
                      name: 'Level 5: A'
                    }
                  ]
                }
              ]
            },
            {
              name: 'Level 3: B'
            },
            {
              name: 'Level 3: C',
              children: [
                {
                  name: 'Level 4: B',
                  children: [
                    {
                      name: 'Level 5: B'
                    }
                  ]
                }
              ]
            }
          ]
        },
        {
          name: 'Level 2: B',
          children: [
            {
              name: 'Level 3: D'
            },
            {
              name: 'Level 3: E',
              children: [
                {
                  name: 'Level 4: C'
                }
              ]
            },
            {
              name: 'Level 3: F'
            }
          ]
        }
      ]
    };
```

**Comment by jpb12** [comment]
This should not be ignored, and is a bug in your code.

You have two nodes with the same name in your JSON ('Level 4: B'), the children of 3: A and 3: C.  React will only render the first one, so your tree will be missing a node.

You can either:
* Change the name of one of the nodes so that they are unique
* Give each node a different property that is unique and override the 'keyProp'

It's not relevant that you see a Node and a Link with the same key in the developer tools.  Keys only have to be unique across a single list in the JavaScript, and the nodes and links are rendered from separate lists in the [code](https://github.com/jpb12/react-tree-graph/blob/ddfed345b9e67f6a0c269d4847f2d534fd0c4252/Components/container.js#L31-L57).

See the [react docs](https://reactjs.org/docs/lists-and-keys.html#keys-must-only-be-unique-among-siblings) for more details.

**Comment by CharlesCarnell** [comment]
Having two nodes in separate objects, nested at different levels, with the same names is a valid use case in my situation.

If my understanding is correct, the warning stems from the library using the property names as React's key. Can the key be made configurable to alleviate this situation?

For instance, each node uses a property of `key` by default, resorting to `name` as a fall back?

**Comment by CharlesCarnell** [comment]
I can now see there is `keyProp` support, which saves a pull request. Can mark as closed.
