### ISSUE TITLE
Using rect instead of circle

### ISSUE THREAD

**Issue by josh-stevens** [jpb12/react-tree-graph#65]
My designer wants a tree that your library works great for, but he wants rectangles with rounded edges rather than circles. This works best with rect tags rather than circle tags. I created a [fork](https://github.com/josh-stevens/react-tree-graph/commit/5d1bfd094e4cf50eda54ff15ba6d2358aa863e1d) where I've create a "rect" boolean prop (which will then be checked and render a rect rather than a circle) and "rectProps" used rather than circleProps. This is a bit redundant since I could have easily just used circleProps, but I felt like it was a  bit confusing to pass circleProps when I'm rendering rects. Maybe there's a better way.

A couple of other small changes on that fork:
- Changed proptype of pathFunc from string to func. It was complaining about receiving the wrong prop when I passed a function but worked fine.
- I also passed "wrappedTextProps" as the last prop to the text element, that way I can overwrite the default dx and dy props given to it.

Let me know if you're interested in a PR. I can use the lib from my fork if not, but wouldn't mind contributing.

**Comment by jpb12** [comment]
> Changed proptype of pathFunc from string to func. It was complaining about receiving the wrong prop when I passed a function but worked fine.

Can you raise a PR for this and we'll release v4.1.1 with this fix? (So as not to require users updating to the breaking changes suggested below)

> I also passed "wrappedTextProps" as the last prop to the text element, that way I can overwrite the default dx and dy props given to it.

Technically a breaking change, although I can't imagine anyone is leaving those props and relying on them being overwritten. Still, I'd suggest batching this with the main change for safety since I'm going to suggest modifications that will make it a breaking change anyway.

>  I created a fork where I've create a "rect" boolean prop (which will then be checked and render a rect rather than a circle) and "rectProps" used rather than circleProps.

I think it would be better if this was implemented more generically like:
`shape: PropTypes.oneOf(['circle', 'rect', 'polygon'])` with a default value of `circle`.
I'm not convinced on `shape` as the name of the prop though. `nodeShape`?

Then there would be a single prop replacing `circleProps` for this shape. Obviously, this is a breaking change so this would be release v5.0.0.

**Comment by josh-stevens** [comment]
That makes a lot of sense, I'll see about making those changes this week or next week.
